### ISSUE TITLE
RPC连接错误

### ISSUE THREAD

**Issue by codeskyblue** [openatx/atx-uiautomator#1]
复现方法，连接之后直接关掉连接，然后重新连接

```
  File "C:\Python27\lib\site-packages\uiautomator\__init__.py", line 137, in __call__
    "%s: %s" % (jsonresult["error"]["data"]["exceptionTypeName"], jsonresult["error"]["message"])
uiautomator.JsonRPCError: JsonRPC Error code: 0, Message: java.lang.IllegalStateException: UiAutomation not connected!
```

**Comment by yanyeustc** [comment]
![image](https://cloud.githubusercontent.com/assets/6022829/17922398/537e1042-6a11-11e6-97a5-bc597b4fe4d2.png)

**Comment by codeskyblue** [comment]
`UiAutomation not connected!`  怀疑是sdk>18的时候会出现，此时的测试使用的是 instrument ，因无法找到进程名，所以无法杀掉响应的进程进行重启

**Comment by codeskyblue** [comment]
quick horiable fix with https://github.com/openatx/atx-uiautomator/commit/8c768f030b74b6d5f94ed4fff45ffd9af284d41b
