### ISSUE TITLE
貌似uiautomater和STF的Provider在同一台机器上面会出现adb争用

### ISSUE THREAD

**Issue by willow-rgb** [openatx/atx-uiautomator#6]
Hi，
最近试了一下把uiautomator放在和STF同一台机器上面，uiautomator同样以systemd方式部署，开机自动重启。结果发现每次重启后，provider都是启动失败。

systemctl stop uiautomator后再
systemctl start stf.provider
就可以正常了

莫非两个会出现ADB的USB争用，不知道你有没有遇到过这个问题。

**Comment by codeskyblue** [comment]
理论上应该不会有问题的，我们公司就是STF+uiautomator混合着使用

**Comment by willow-rgb** [comment]
STF用的是他们自己搞的adbkit
你们有对uiautomator做过adb方面的改造吗？

**Comment by codeskyblue** [comment]
这个项目就是改动过的，但是改动的很少，因为使用的时候没有遇到什么问题

**Comment by willow-rgb** [comment]
好的，之前拉的xiaocong版本，我来研究一下你的这个项目。。

**Comment by codeskyblue** [comment]
区别不怎么大，只是为了版本管理方便，我才fork一个出来
