### ISSUE TITLE
UTF-7对于中文的支持还是不够完美，中文标点符号经常出现乱码。

### ISSUE THREAD

**Issue by willow-rgb** [openatx/atx-uiautomator#7]
发现一个新的工程，建议尝试一下

https://github.com/senzhk/ADBKeyBoard

**Comment by codeskyblue** [comment]
确认下有哪些符号，是` ，。`这种吗？

**Comment by willow-rgb** [comment]
我遇到的一个典型的就是中文问号，比如: "在吗？"

**Comment by willow-rgb** [comment]
app-uiautomator-test.apk
app-uiautomator.apk

问下，这两个APK的源码是在哪里可以找到？

**Comment by codeskyblue** [comment]
https://github.com/xiaocong/android-uiautomator-server
