### ISSUE TITLE
获取子节点bug

### ISSUE THREAD

**Issue by a735465047** [openatx/atx-uiautomator#8]
尝试使用d(resourceId="...").child(className="...")[X]方法获取到一个节点的子节点的个数是1个，无法获取多个子节点，如果使用d(resourceId="...").child(textContains="...").exists可以查看到时存在该子节点的，并且d(resourceId="...").info中子节点的数量也是正确的，经查看源代码发现应该是uiautomator只能获取一个子节点，即使获取的是多个子节点也只返回一个。

**Comment by codeskyblue** [comment]
既然如此，解决不了，那就算了

**Comment by a735465047** [comment]
为什么不解决啊

**Comment by codeskyblue** [comment]
你想怎么用啊

**Comment by a735465047** [comment]
有多个child的时候，可以通过下标之类的选择第几个child


735465047@qq.com
 
Sender: shengxiang
Send Time: 2017-03-09 16:21
Receiver: openatx/atx-uiautomator
cc: wowo; Author
Subject: Re: [openatx/atx-uiautomator] 获取子节点bug (#8)
你想怎么用啊

**Comment by codeskyblue** [comment]
现在也可以呀，你仔细看文档
